name: Auto Update Last Updated Date

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Current Date
        id: date
        run: echo "date=$(date '+%B %d, %Y')" >> $GITHUB_OUTPUT

      - name: Update HTML Files
        run: |
          for file in index.html about.html contact.html; do
            if [ -f "$file" ]; then
              sed -i "s|<span id=\"last-updated-date\">.*</span>|<span id=\"last-updated-date\">${{ steps.date.outputs.date }}</span>|" "$file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update last updated date"
          git push